spring:
  # session配置
  session:
    timeout: 86400
    store-type: redis
    redis:
      namespace: "hello"

  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 3

server:
  port: 8080
    #port: 8081